package javax.microedition.amms;

/**
 * MediaProcessorListener is an interface that may be used to receive
 * events generated by a MediaProcessor.
 */
public interface MediaProcessorListener {
	String PROCESSOR_REALIZED = "processRealized";
	String PROCESSING_STARTED = "processingStarted";
	String PROCESSING_STOPPED = "processingStopped";
	String PROCESSING_COMPLETED = "processingCompleted";
	String PROCESSING_ABORTED = "processingAborted";
	String PROCESSING_ERROR = "processingError";

	void mediaProcessorUpdate(MediaProcessor processor, String event, Object eventData);
}
